In [11]:
import pandas as pd

raw_puzzles = pd.read_csv("grid-puzzles.csv")
raw_puzzles.head()

,Grid,Difficulty,Story,Clues,Table,Options,Puzzle,Key
0,3x4,Easy,The Abbeville K-9 Academy trains dogs for use ...,1.The canine that graduated in May was either ...,+----------+--------+------------+\n| Months ...,"Officers: Daugherty, Lyons, Quinn, Salinas\nDo...",\nStory:\nThe Abbeville K-9 Academy trains dog...,b59fe032-5072-4a46-8201-fc2f04519d39
1,3x4,Easy,The Maplewood Canine Training Center prepares ...,1.The animal that finished training in June wa...,NaN,"Departments: Parks, Fire, Police, Animal Contr...",Story:\nThe Maplewood Canine Training Center p...,817f4cce-d4e9-42b7-b4fe-2989eee94635
2,3x4,Easy,"The Byronville Gaming Club holds one ""game nig...",1.The board game played in January was hosted ...,+----------+---------+---------+\n| Months |...,"Hosts: Adrian, Bonnie, Vera, Wendy\nGames: And...",\nStory:\nThe Byronville Gaming Club holds one...,7fa7f045-fb46-4205-8999-2c43681a0f1b
3,3x4,Easy,"The Maplewood Puzzle Society hosts a monthly ""...",1.The puzzle game played in March was hosted b...,NaN,"Hosts: Claire, Ethan, Liam, Sophie\nGames: Qua...",Story:\nThe Maplewood Puzzle Society hosts a m...,5871cd6f-bea7-4b04-a29e-c83afc68e51b
4,3x4,Easy,Mayor Price has promised to get the streets of...,1.The four projects are the job starting in Ju...,+----------+-----------+-----------+\n| Months...,"Mangers: Bill Bonner, Cal Craft, Hal Hamilton,...",\nStory:\nMayor Price has promised to get the ...,ffe608dd-aa49-4dce-a57d-6543c0266335

In [12]:
partial = pd.read_csv("partial_solution.csv")
partial.head(n=6)

,Key,Puzzle,Code,Solution
0,f51c0d33c204e7fdeb1f5d1a934d517e,Story:\nMatch each auctioned spider specimen t...,% ============================================...,"[('45', 'charles'), ('75', 'freddie'), ('60', ..."
1,08e3c937b0b979a9abe1eab5aa049fdc,Story:\nGarrett County has set up a number of ...,% ============================================...,"[('400', 'books_4_u'), ('250', 'dream_machine'..."
2,a996b44da7d0cfe5fd1d3ae42a63031b,Story:\nThe Appalachian Folk Art Festival's wo...,% ============================================...,"[('8', 'butternut'), ('20', 'cherry'), ('12', ..."
3,70043e4797ce188c5dff5e6195703f15,"Story:\nMary has 42 different grandchildren, a...",% ============================================...,"[('april_7th', 'bryan'), ('april_15th', 'guy')..."
4,504f9d954df699d00ad2e87449c98dc8,"Story:\nErnest, the curator at the Eastwick Hi...",% ============================================...,"[('1920', 'cairo'), ('1912', 'london'), ('1928..."
5,d054399c77e80e2d10de3b85df415b5d,Story:\nThe local foodie club met at Chez Mart...,% ============================================...,"[('p24_99', 'frances'), ('p26_99', 'genevieve'..."

In [13]:
raw_puzzles = raw_puzzles[["Puzzle"]]
raw_puzzles['Puzzle'] = raw_puzzles['Puzzle'].str.strip()

partial['Puzzle'] = partial['Puzzle'].str.strip()
merged = pd.merge(raw_puzzles, partial, on=["Puzzle"], how="left")
merged.head()

                                              Puzzle  Key Code Solution
0  Story:\nThe Abbeville K-9 Academy trains dogs ...  NaN  NaN      NaN
1  Story:\nThe Maplewood Canine Training Center p...  NaN  NaN      NaN
2  Story:\nThe Byronville Gaming Club holds one "...  NaN  NaN      NaN
3  Story:\nThe Maplewood Puzzle Society hosts a m...  NaN  NaN      NaN
4  Story:\nMayor Price has promised to get the st...  NaN  NaN      NaN

In [14]:
import hashlib
from uuid import uuid4

for index, row in merged.iterrows():
    # Generate an MD5 hash
    unique_key = hashlib.md5(str(row['Puzzle']).encode()).hexdigest()
    merged.at[index, 'Key'] = unique_key

merged.to_csv('asp-tbd.csv', index=False)

In [15]:
filled = 1 - merged['Code'].isna().sum()/len(merged)
print(f'Filled Pct: {round(filled*100,2)}%')

Filled Pct: 0.28%