In [108]:
def getKey(x: str):
    import hashlib 
    x = str(x).strip().lower()
    return hashlib.md5(x.encode('utf-8')).hexdigest()

In [109]:
import pandas as pd 

main_puzzle = pd.read_csv("grid-puzzles-sample.csv")
main_puzzle['Key'] = main_puzzle['Puzzle'].apply(lambda x: getKey(x))
print(main_puzzle.shape)
main_puzzle.head()

(36, 8)

,Grid,Difficulty,Story,Clues,Table,Options,Puzzle,Key
0,3x4,Challenging,Match each auctioned spider specimen to its ow...,1.Freddie's purchase cost 15 dollars more than...,+----------+-----------+-----------+\n| Prices...,"Spiders: archaenido, cart spider, darkback, wh...",Story:\nMatch each auctioned spider specimen t...,f51c0d33c204e7fdeb1f5d1a934d517e
1,3x4,Challenging,At the annual Riverside Vintage Watch Exchange...,1.The Tissot watch was either the timepiece wi...,NaN,"Face Colors: blue, green, red, silver\nBrands:...",Story:\nAt the annual Riverside Vintage Watch ...,8954403c2015072bdb7ee5df65f94159
2,3x4,Easy,Garrett County has set up a number of successf...,"1.""Tiny Tomes"" has 350 books.\n2.The mobile li...",+---------+---------------+-----------+\n| B...,"Drivers: Antonio, Gene, Leroy, Patsy\nBookmobi...",Story:\nGarrett County has set up a number of ...,08e3c937b0b979a9abe1eab5aa049fdc
3,3x4,Easy,The Appalachian Folk Art Festival's woodcarvin...,"1.The four carvings were the wolf piece, the 1...",+-----------+--------------+------------+\n| H...,"Subjects: deer, eagle, fish, wolf\nWood Types:...",Story:\nThe Appalachian Folk Art Festival's wo...,a996b44da7d0cfe5fd1d3ae42a63031b
4,3x4,Moderate,Emma planned a week of healthy snack sessions ...,1.The almond energy bar contains somewhat fewe...,NaN,"Days: Wednesday, Thursday, Friday, Saturday\nS...",Story:\nEmma planned a week of healthy snack s...,bb6f3d825f2c06ca3bf3b45b03cb0c7a

In [110]:
asp_solution = pd.read_csv("gflash25/grid-puzzles-sample-asp.csv")
asp_solution['Key'] = asp_solution["Puzzle"].apply(lambda x: getKey(x))
print(asp_solution.shape)
asp_solution.head()

(6, 4)

,Key,Puzzle,Code,Solution
0,f51c0d33c204e7fdeb1f5d1a934d517e,Story:\nMatch each auctioned spider specimen t...,% ============================================...,"[('45', 'charles'), ('75', 'freddie'), ('60', ..."
1,08e3c937b0b979a9abe1eab5aa049fdc,Story:\nGarrett County has set up a number of ...,% ============================================...,"[('400', 'books_4_u'), ('250', 'dream_machine'..."
2,a996b44da7d0cfe5fd1d3ae42a63031b,Story:\nThe Appalachian Folk Art Festival's wo...,% ============================================...,"[('8', 'butternut'), ('20', 'cherry'), ('12', ..."
3,70043e4797ce188c5dff5e6195703f15,"Story:\nMary has 42 different grandchildren, a...",% ============================================...,"[('april_7th', 'bryan'), ('april_15th', 'guy')..."
4,504f9d954df699d00ad2e87449c98dc8,"Story:\nErnest, the curator at the Eastwick Hi...",% ============================================...,"[('1920', 'cairo'), ('1912', 'london'), ('1928..."

In [111]:
df = pd.merge(main_puzzle, asp_solution, on=["Key", "Puzzle"])
df = df[['Key', 'Puzzle', 'Code', 'Solution']]
prev_shape = df.shape
df_good = df[df['Solution'] != 'Incorrect verification code']
df_bad = df[df['Solution'] == 'Incorrect verification code']
df_good.to_csv('dataset.csv', index=False)
print(f'Before: {prev_shape},\nGood: {df_good.shape},\nBad: {df_bad.shape}')

Before: (6, 4),
Good: (6, 4),
Bad: (0, 4)